---
- hosts: all
  tasks:

    - name: Update cache
      apt: update_cache=yes

    - name: Chrome beta
      shell: |
        chromeDev=chromebeta.deb
        if [ ! -f $chromeBeta ]; then
            wget -q -O $chromeBeta 'https://dl.google.com/linux/direct/google-chrome-beta_current_amd64.deb'
            dpkg -i $chromeBeta
            #rm $chromeBeta
        else
            dpkg -i $chromeBeta
        fi
        apt install -f -y
